pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    environment {
        COURSE = 'Jenkin'
    }

    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('init-section') {
            steps {
                script {
                    withAWS(region:'us-east-1', credentials: 'aws-creds'){
                    sh '''
                    cd 00-vpc/
                    echo "present in iniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiittttt"
                    terraform init

                       '''
                    }
                }
            }
        }
        stage('plan-section') {
            steps {
                script {
                    withAWS(region:'us-east-1', credentials: 'aws-creds'){

                    sh '''
                    echo "present in plaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnn"
                    cd 00-vpc/
                    terraform plan

                       '''
                    }
                }
            }
        }

        stage('Deploy') {
            input {
                message 'Should we continue?'
                ok 'Yes, we should.'
                submitter 'alice,bob'
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }

            steps {
                script {
                    withAWS(region:'us-east-1', credentials: 'aws-creds'){
                    sh '''
                        cd 00-vpc/
                        terraform apply -auto-approve

                       '''
                    }
                }
            }
        }
    }

        // --------------------------post build--------------------
        post {
        always {
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'Success---------------'
        }
        failure {
            echo 'failure---------------'
        }
        aborted {
            echo 'someone -aborted--------------------------------'
            echo 'may be timeeout  -aborted--------------------------------'
        }
        }
}
