pipeline {

agent {
    node {
        label 'AGENT-1'
        
    }

}


environment { 
        COURSE = 'Jenkin'
    }
 
    options {
        timeout(time: 60, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    stages {
        stage('init-section') {
            steps {
                script{
                    sh """
                    echo "present in iniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiittttt"
                        terraform init 

                       """ 
                }
            }
        }
        stage('plan-section') {
            steps {
                script{
                    sh """
                    echo "present in plaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnn"
                        terraform plan 

                       """ 
                }
            }
        }

        stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }

            steps {
                script{
                    sh """
                        terraform apply -auto-approve 

                       """ 
                }
            }
        }

    }

    // --------------------------post build--------------------
        post { 
        always { 
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success{
            echo "Success---------------"
        }
        failure{
            echo "failure---------------"
        }
        aborted{
            echo "someone -aborted--------------------------------"
            echo "may be timeeout  -aborted--------------------------------"
        }
    }
}