pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    environment {
        COURSE = 'Jenkin'
    }

    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('init-section') {
            steps {
                script {
                    withAWS(region:'us-east-1', credentials: 'aws-creds') {
                        sh '''
                    cd 10-sg/
                    echo "present in inti"
                    terraform init

                       '''
                    }
                }
            }
        }
        stage('plan-section') {
            steps {
                script {
                    withAWS(region:'us-east-1', credentials: 'aws-creds') {
                        sh '''
                    echo "present in plan"
                    cd 10-sg/
                    terraform plan

                       '''
                    }
                }
            }
        }

        stage('Deploy') {
            input {
                message 'Should we continue?'
                ok 'Yes, we should.'
                submitter 'alice,bob'
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }

            steps {
                script {
                    withAWS(region:'us-east-1', credentials: 'aws-creds') {
                        sh '''
                        cd 10-sg/
                        terraform apply -auto-approve

                       '''
                    }
                }
            }
        }
        stage('Parallel Trigger') {
            parallel {
                stage('Bastion') {
                    steps {
                        script {
                            build job: '20-bastion',
                             wait: false //It does not need to wait for the completion of VPC
                            propagate: false // when thereis failure in d/s it should not affect u/s
                        }
                    }
                }
                stage('SG-RULES') {
                    steps {
                        script {
                            build job: '30-sg-rules',
                             wait: false //It does not need to wait for the completion of VPC
                            propagate: false // when thereis failure in d/s it should not affect u/s
                        }
                    }
                }
                stage('ECR-REPO') {
                    steps {
                        script {
                            build job: '40-ecr',
                             wait: false //It does not need to wait for the completion of VPC
                            propagate: false // when thereis failure in d/s it should not affect u/s
                        }
                    }
                }
                stage('ACM') {
                    steps {
                        script {
                            build job: '70-acm',
                             wait: false //It does not need to wait for the completion of VPC
                            propagate: false // when thereis failure in d/s it should not affect u/s
                        }
                    }
                }
                stage('EKS') {
                    steps {
                        script {
                            build job: '90-eks',
                             wait: false //It does not need to wait for the completion of VPC
                            propagate: false // when thereis failure in d/s it should not affect u/s
                        }
                    }
                }
            }
        }
        stage('ALB') {
                    steps {
                        script {
                            build job: '80-frontend-alb',
                            wait: false //It does not need to wait for the completion of VPC
                            propagate: false // when thereis failure in d/s it should not affect u/s
                        }
                    }
        }
    }

        // --------------------------post build--------------------
        post {
        always {
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'Success---------------'
        }
        failure {
            echo 'failure---------------'
        }
        aborted {
            echo 'someone -aborted--------------------------------'
            echo 'may be timeeout  -aborted--------------------------------'
        }
        }
}
